//  
//  PokemonModuleInteractor.swift
//  Pokemon-CaseStudy
//
//  Created by Hasan Dag on 3.11.2022.
//
//  This file was generated by I-VIPER Xcode Templates
//  so you can design a more scalable and maintainable
//  design to your iOS projects, see https://github.com/fdorado985/I-VIPER
//

import Foundation

class PokemonModuleInteractor {
  // MARK: - Properties

  weak var presenter: PokemonModulePresenterInterface?
}

// MARK: - PokemonModuleInteractorInterface

extension PokemonModuleInteractor: PokemonModuleInteractorInterface {}
