//  
//  PokemonModuleRouter.swift
//  Pokemon-CaseStudy
//
//  Created by Hasan Dag on 3.11.2022.
//
//  This file was generated by I-VIPER Xcode Templates
//  so you can design a more scalable and maintainable
//  design to your iOS projects, see https://github.com/fdorado985/I-VIPER
//

import UIKit

class PokemonModuleRouter {
  // MARK: - Properties

  weak var presenter: PokemonModulePresenter?

  // MARK: - Methods

  static func createModule() -> PokemonModuleViewController {
    let router = PokemonModuleRouter()
    let presenter = PokemonModulePresenter()
    let interactor = PokemonModuleInteractor()
    let view = PokemonModuleViewController()

    presenter.interactor = interactor
    presenter.router = router
    presenter.view = view
    view.presenter = presenter
    interactor.presenter = presenter
    router.presenter = presenter

    return view
  }
}

// MARK: - PokemonModuleRouterInterface

extension PokemonModuleRouter: PokemonModuleRouterInterface {}
